### ISSUE TITLE
Can you guys merge with another repo to unify progress?

### ISSUE THREAD

**Issue by FerLuisxd** [xl3lackout/Erupe#10]
This [repo](https://github.com/ricochhet/Erupe) also made some enhacements to the server.
As we would see better progress if you guys worked together

**Comment by xl3lackout** [comment]
What kind of enhancements have they added? The only file thats been really modified in a year was handlers.go, and that seems to be handled by Megax.

**Comment by rhobiusvoid** [comment]
That repo is widly out of date compared with this repo, to the point that merging it would cause massive issues in actually running the server. That's likely why this repo is standalone as opposed to being a fork of that one.
The people who link to that repo don't seem like they want to work with the people behind this repo too however, so keep that in mind regardless of what they say.

If you want to help contribute towards the game in-question's life, you can just make a commit here and your work here might see more fruition.

**Comment by ricochhet** [comment]
Yea, a similar issue was opened in my repo. Like I've said there, I assumed this to be much further ahead in terms of development. Mine is primarily the same as the one that was "deleted," with a few ease-of-use additions on top. 

I don't intend to merge any forks. There would be no point in me doing that either, although it gets a lot of traffic, it would be an unnecessary third step for anyone doing development, as I don't have the time nor intentions to do much beyond simply maintaining the repo. 

If either party really wanted to do that, I would move the current code to a different branch and start fresh in the main branch with your code, but that doesn't really solve any problems, if any, it'll create more.

May as well keep things the way they are. I appreciate that people are keeping up with the development on the server though, you guys are doing good work. Keep it up.
