### ISSUE TITLE
Garden cat

### ISSUE THREAD

**Issue by halexys** [xl3lackout/Erupe#18]
The garden cat craches de server. I fixed it in muy local server.

**Comment by xl3lackout** [comment]
Yeah I apologize. There was a mix up with that commit as it was based off of a development fork and the required tables weren't included in the SCHEMA.sql file for the ravi update. For future reference the command to fix this in PGAdmin Query tool is such (If someone doesnt know what that is, right click your erupe DB and hit query tool, copy and paste this inside):

BEGIN;
ALTER TABLE IF EXISTS public.users
ADD COLUMN item_box bytea;
END;

**Comment by halexys** [comment]
Also. In the characters table should be an item_box column. It have a conflict with the one in users table when the server make the "Select" request. It's says that the column item_box is ambiguous or something like that.
