### ISSUE TITLE
delete Golang dependencies folder from git history

### ISSUE THREAD

**Issue by Tsugami** [xl3lackout/Erupe#32]
Currently, the repository is heavy for download and local development (in my IDE at least). As Golang dependencies folder uploaded and still in git history even after deleting it in #19

**Use [BFG](https://rtyley.github.io/bfg-repo-cleaner/) for delete from git history.** 

I deleted it from a private repository and it was much lighter, **58811** to **1872**

before:
![image](https://user-images.githubusercontent.com/27602189/178092745-4c7cb4eb-c275-4e19-95c3-6c8069bb4765.png)
after:
![image](https://user-images.githubusercontent.com/27602189/178092752-3c36e8ba-f3e2-420e-b33d-5be91ac43bea.png)

#### How to use:
> Note: All PR and branches needed to be deleted or closed before running it.

1. Download [BFG](https://rtyley.github.io/bfg-repo-cleaner/) and Java (BFG made in Java).
2. Move BFG to Erupe folder
3. Backup!
4. Run `java -jar bfg-1.14.0.jar --delete-folders go`

Done! Now push to main with -f: `git push origin main -f`

> Probably all forks need to update their branches with --force to contribute new PRs

**Comment by sekaiwish** [comment]
The repository has been cleaned.

**Comment by Tsugami** [comment]
niceee!
