### ISSUE TITLE
How to change the number of people in land

### ISSUE THREAD

**Issue by Ivanov-G** [xl3lackout/Erupe#34]
Currently, the capacity of the introductory ward has become 0 and it is not possible to enter the world with a new character.
Where can I adjust this capacity?

**Comment by Evotushon** [comment]
In the `config.json`, change the highlighted value 
![image](https://user-images.githubusercontent.com/87574203/181812912-9b8c054f-c830-426b-a26e-cd495892fab3.png)
to whicever number you want. I don't know if the introduction entry works though
