### ISSUE TITLE
does anyone have a fix for not being able to get past the capcom online games logo?

### ISSUE THREAD

**Issue by soulmizute** [xl3lackout/Erupe#8]
![image](https://user-images.githubusercontent.com/86098610/158072757-b0507e12-5fcc-412b-aa6a-990e65929dc9.png)
this is my issue and im trying everything i can think of. it could be something to do with my client bu ti really dont know

**Comment by superkerokero** [comment]
Sounds like a client program issue.

Try the client provided in the links from the [pastebin](https://pastebin.com/QqAwZSTC), so far it works fine for me.

**Comment by soulmizute** [comment]
it was due to the game trying to connect to the registry files from the capcom files that were on my pc. ive been using the astebin the entire time ive been playing frontier
